### PR TITLE
Fix/sigimm 47  server logs

### LINKED ISSUE #17: Feat: Limit search admin error logs to be core specific
When viewing the solr logs in the cms under /admin/searchadmin/Firesphere-SolrSearch-Models-SolrLog , logs are not displayed for the current solr core but every core on the server.

The module makes a request for logs as follows:
`$response = $this->client->get('solr/admin/info/logging', $options);`

This returns the entire server log. If there is a way to modify this request to retrieve only logs relating to a specific core then we should probably do that. Alternatively, on retrieving the log data we could filter by the core value in each log. Some errors will not have a core value and we will likely want to capture those.

Log data is in the following format:
```
time	"2025-06-16T02:20:36.131Z"
level	"WARN"
logger	"org.apache.solr.core.SolrConfig"
message	"Ignored deprecated enableRemoteStreaming in config; use sys-prop"
core	"ss5-modules-dev1-ss5-modules"
trace_id	"solr-dev18.signify.nz-5526"
```

### PR DESCRIPTION
**Pull request by sig-shadae**
More information can be found at #17.

### CODE REVIEW

File: src/Helpers/SolrLogger.php [hunk 1]
```diff
@@ -115,14 +117,24 @@ public function saveSolrLog($type = 'Query'): void
...
+        }
 
         foreach ($arrayResponse['history']['docs'] as $error) {
-            $filter = [
-                'Timestamp' => $error['time'],
-                'Index'     => $error['core'] ?? 'x:Unknown',
-                'Level'     => $error['level'],
-            ];
-            $this->findOrCreateLog($type, $filter, $error);
+            if (in_array($error['core'], $indexNames) == true || $error['core'] == '') {
```
Comment (sig-mmiddleton) [inline src/Helpers/SolrLogger.php]: Can $error['core'] ever resolve to null? Will this array key always be present? I'm thinking we can write this in a more error safe way. Perhaps:
```
$core = $error['core'] ?? null;

if (in_array($core, $indexNames) || $core === '' || $core === null) {
```

**Review by sig-mmiddleton — CHANGES_REQUESTED** [review]
Changes requested

File: src/Helpers/SolrLogger.php (hunk 1 above)
Comment (sig-shadae) [reply src/Helpers/SolrLogger.php]: Looking at some previous logs, I see some instances where index is 'x:Unknown', set by checking core with `$core ?? 'x:Unknown'`. Therefore I'd say $error['core'] can resolve to null. 
I've updated the code as per your suggestion.

**Review by sig-mmiddleton — APPROVED** [review]
Looks good to me
